### PR TITLE
Use sqlite triggers for seriesmeta

### LINKED ISSUE #42: Support adding series metadata to books before being imported
See the comments starting from https://github.com/shermp/Kobo-UNCaGED/issues/22#issuecomment-538555826.

### PR DESCRIPTION
**Pull request by geek1011**
* Now works before importing content.
* Still can be used at the same time as Calibre.
* Can optionally persist metadata.
* Can optionally not overwrite existing metadata.
* Now supports EPUB3-style series metadata

closes #42

cc @shermp @NiLuJe @jackiew1

### CODE REVIEW

**Comment by shermp** [comment]
I don't seen any problems that jump out at me.

What is the reason why you've chosen ImageID instead of ContentID?

**Comment by geek1011** [comment]
> What is the reason why you've chosen ImageID instead of ContentID?

ImageID only appears on the main book entries, unlike ContentID, which appears on the main entry as well as the TOC entries.

**Comment by shermp** [comment]
Fair enough. I use the ContentType column to filter out chapters, but I guess ImageID works as well.

**Comment by shermp** [comment]
Note on series number, their is also a column called `seriesNumberFloat`. I'm not sure if Nickel actually uses that figure or not.

Maybe it's used for sorting, if the series number text is not sortable (eg, roman numerals)?

**Comment by shermp** [comment]
What is your thinking behind the `UPDATE` trigger? The whole trigger idea was to update metadata after Nickel has inserted the new row, so the `INSERT` trigger makes sense. However, to my thinking, if the record already exists in the content table, one can just update it directly without needing a trigger.

Am I missing something?

**Comment by geek1011** [comment]
I've never seen seriesNumberFloat used for anything (or most of the lowercase ones for that matter) meaningful, if at all. Also, you can put floats in SeriesNumber (that's why it's a TEXT column). I'll check the firmware just to be sure.

My thinking behind the content UPDATE trigger was for the persist option, and just in case Kobo overwrites all the values on after adding the row during import either now or in the future.

About the record already existing, look at the last two triggers for INSERTs and UPDATEs to the _seriesmeta table.

**Comment by geek1011** [comment]
OK, so I was just testing this, and it works well in general. Although, `--persist` will need to be made default.

If you run seriesmeta with the books already imported, the changes show up immediately and stay there like before. The persist option doesn't affect this.

If you run seriesmeta with books pending import, the changes are made during the import, but only show up after another USB connection or a reboot. If you open (or do any action on) the book before the metadata shows, the metadata will disappear unless the persist option is set.

If the persist option is set and you delete a book, the row from the seriesmeta table gets removed correctly.

There is negligible performance impact with or without the persist option, even with large (~2000 book) libraries. There also do not appear to be any side effects.

If I'm missing any tests, tell me, and I'll do them.

And, one thing I noticed while testing, unless I did something wrong, it appears that since the new reader came about, the covers are now generated from the first page rather than the linked cover image in the OPF. @davidfor, is this expected? If so, I'm also going to write a covergen tool to pre-generate proper covers for books.

**Comment by shermp** [comment]
> If you run seriesmeta with books pending import, the changes are made during the import, but only show up after another USB connection or a reboot. If you open (or do any action on) the book before the metadata shows, the metadata will disappear unless the persist option is set.

Awww. I was hoping Nickel would show the updated metadata without needing a reboot or USB session :(

Although, logically thinking about it, that would make sense.

**Comment by geek1011** [comment]
At least it can all be done in a single USB connection. I may be able to patch this, though.

**Comment by shermp** [comment]
I don't know why I was thinking it might work. I've got the syslog dump, and after importing, there's no `SELECT` on the `content` table so doh...

**Comment by geek1011** [comment]
@shermp, I'm ready for this to be reviewed.

**Comment by shermp** [comment]
Nothing immediately jumps out as being an issue.

Does kepubify support external SD cards? Because this code does not appear to. I don't know if you have any plans to add this support.

**Comment by geek1011** [comment]
> Does kepubify support external SD cards? Because this code does not appear to. I don't know if you have any plans to add this support.

Kepubify itself doesn't have any issues, but I'm not familiar with how Kobo handles external SD cards (and I don't have a Kobo which supports it), so I'm not planning to implement that myself.

**Comment by shermp** [comment]
As a side-note, do you have any ideas on how it might be possible to patch Nickel to re-read the DB?

Maybe by somehow triggering the filesync function (or whatever it's called) a second time perhaps?

**Comment by geek1011** [comment]
@shermp, no, it isn't possible, but I might be able to do it with a LD_PRELOAD hack.

I'm going to merge this now, as I just tested it with my new Clara without any issues.

**Comment by geek1011** [comment]
@davidfor, you may want to update the Calibre driver to properly handle when persistence is used. You can either remove the row from the _seriesmeta table or you can update the metadata in it if it exists.

**Comment by shermp** [comment]
> @shermp, no, it isn't possible, but I might be able to do it with a LD_PRELOAD hack.

Awww, that's a shame. Ah well.

**Comment by davidfor** [comment]
@geek1011: No, I do not want to add support for this hack in the driver. Overall, using seriesmeta is inconsistent with using calibre. And I really don't expect there will be many users of it. If I get enough complaints, I'll reconsider. But, if I ever do, it will be throwing an error and just stopping.

What you need to do is add into your instructions to turn off the metadata updating options in the drivers and the "Do not treat replacements as new books" option. Those are the only places the content table is updated so that should prevent any problems. And to not use any of the metadata updating options in Kobo Utilities.

**Comment by geek1011** [comment]
@davidfor: OK, that's fine. The issue was more that the updates would be silently discarded when using persistence, not that any problems would occur (I was considering having it go both ways, but I didn't like the possibility of endless loops if Kobo decided to enable trigger recursion in their sqlite build). I'll add a FAQ about that. In the end, it probably won't even be noticeable, as (correct me if I'm wrong) Calibre puts the series metadata tags into the books transferred to the Kobo, so the metadata would match either way.

**Comment by davidfor** [comment]
The issue would depend on some timing. Calibre puts the series info in the book when it is sent, but, the driver updates the database on the next connection. If the series info is changed in calibre, it will be updated in the database on the next connect. The triggers would replace this with whatever was last written to the _seriesmeta tables. Unless the books were also updated and seriesmeta run for these books.

I am baffled by the decision to use the ImageID as the key. The contentId is unique to the book row that needs to be updated. The ToC entries are unique as they use the books contentId plus the name of the internal file and potentially the fragment.

**Comment by geek1011** [comment]
Ok, that's almost what I thought. I will probably disable persistence by default when Calibre is used, and add a warning about that.

Regarding the decision to use ImageID as the key, I don't recall the reasons why I chose that (it was a few months ago). TBH, it might have just been an arbitrary decision, as both ways work (and it was how I was keeping track of the books previously).

**Pull request merged**
